@MyEducation.WebAPI_HostAddress = https://localhost:7065

GET {{MyEducation.WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{MyEducation.WebAPI_HostAddress}}/hok/students

###

GET {{MyEducation.WebAPI_HostAddress}}/tec/students

###
